"""Memory type constants — mirrors frontend src/memory/core/types.ts."""

NodeTypeConstants = {
    "CONVERSATION": "conversation",
    "EXECUTION": "execution",
    "WORKFLOW": "workflow",
    "BROWSER_SESSION": "browser:session",
    "BROWSER_PAGE": "browser:page",
    "BROWSER_BOOKMARK": "browser:bookmark",
    "VOICE_SESSION": "voice:session",
    "VOICE_COMMAND": "voice:command",
    "VISION_CAPTURE": "vision:capture",
    "VISION_ANNOTATION": "vision:annotation",
    "GENERATED_FILE": "file:generated",
    "REFERENCED_FILE": "file:referenced",
    "KNOWLEDGE_STATEMENT": "knowledge:statement",
    "KNOWLEDGE_SUMMARY": "knowledge:summary",
    "KNOWLEDGE_ENTITY": "knowledge:entity",
    "ARTIFACT": "artifact",
    "NOTE": "note",
    "TEMPLATE": "template",
    "PROJECT": "project",
    "COLLECTION": "collection",
    "TAG": "tag",
    "PREFERENCE": "preference",
    "REMINDER": "reminder",
    "TASK": "task",
    "PERSON": "person",
    "ORGANIZATION": "organization",
    "LOCATION": "location",
    "PLUGIN_ACTION": "plugin:action",
    "CUSTOM": "custom",
}

EdgeTypeConstants = {
    "CONTAINS": "contains",
    "PRODUCES": "produces",
    "DERIVES_FROM": "derives_from",
    "REFERENCES": "references",
    "BELONGS_TO": "belongs_to",
    "GENERATED": "generated",
    "USES": "uses",
    "MENTIONS": "mentions",
    "RELATED_TO": "related_to",
    "PINNED": "pinned",
    "SEQUENCES": "sequences",
    "CONTRIBUTES_TO": "contributes_to",
    "CONFIGURES": "configures",
    "OBSERVES": "observes",
    "TRANSFORMS": "transforms",
    "CUSTOM": "custom",
}

NODE_SUPER_TYPES = {
    "action": {"description": "Actions and executions"},
    "observation": {"description": "Observations and sensory data"},
    "knowledge": {"description": "Knowledge and information"},
    "artifact": {"description": "Generated artifacts"},
    "entity": {"description": "Real-world entities"},
    "meta": {"description": "System and metadata"},
}

DEFAULT_NODE_TYPES = [
    {"name": "conversation", "superType": "action", "description": "A conversation session",
     "allowedEdgeTypes": ["contains", "references", "related_to"],
     "allowedAsTargetFor": ["belongs_to", "references"], "defaultMetadata": {}},
    {"name": "execution", "superType": "action", "description": "A tool or function execution",
     "allowedEdgeTypes": ["produces", "references", "related_to"],
     "allowedAsTargetFor": ["contains", "references"], "defaultMetadata": {}},
    {"name": "workflow", "superType": "action", "description": "A multi-step workflow",
     "allowedEdgeTypes": ["contains", "sequences", "produces"],
     "allowedAsTargetFor": ["contains"], "defaultMetadata": {}},
    {"name": "browser:session", "superType": "observation", "description": "A browser automation session",
     "allowedEdgeTypes": ["contains", "references"],
     "allowedAsTargetFor": ["belongs_to", "produces"], "defaultMetadata": {}},
    {"name": "browser:page", "superType": "observation", "description": "A browsed web page",
     "allowedEdgeTypes": ["references", "mentions", "contains"],
     "allowedAsTargetFor": ["contains", "references"], "defaultMetadata": {}},
    {"name": "knowledge:statement", "superType": "knowledge",
     "description": "A factual knowledge statement",
     "allowedEdgeTypes": ["derives_from", "references", "related_to", "contributes_to"],
     "allowedAsTargetFor": ["derives_from", "references", "mentions", "contributes_to"],
     "defaultMetadata": {}},
    {"name": "knowledge:summary", "superType": "knowledge",
     "description": "A summary of knowledge",
     "allowedEdgeTypes": ["derives_from", "references"],
     "allowedAsTargetFor": ["derives_from"], "defaultMetadata": {}},
    {"name": "knowledge:entity", "superType": "knowledge",
     "description": "A knowledge entity",
     "allowedEdgeTypes": ["related_to", "references", "belongs_to"],
     "allowedAsTargetFor": ["related_to", "references", "mentions"], "defaultMetadata": {}},
    {"name": "artifact", "superType": "artifact", "description": "A generated artifact",
     "allowedEdgeTypes": ["references", "related_to"],
     "allowedAsTargetFor": ["produces", "references"], "defaultMetadata": {}},
    {"name": "file:generated", "superType": "artifact", "description": "A generated file",
     "allowedEdgeTypes": ["references", "related_to"],
     "allowedAsTargetFor": ["produces", "references", "generated"], "defaultMetadata": {}},
    {"name": "note", "superType": "artifact", "description": "A user note",
     "allowedEdgeTypes": ["references", "contains", "related_to"],
     "allowedAsTargetFor": ["contains", "references"], "defaultMetadata": {}},
    {"name": "project", "superType": "meta", "description": "A project container",
     "allowedEdgeTypes": ["contains", "configures"],
     "allowedAsTargetFor": ["belongs_to"], "defaultMetadata": {}},
    {"name": "collection", "superType": "meta", "description": "A collection of items",
     "allowedEdgeTypes": ["contains", "references"],
     "allowedAsTargetFor": ["belongs_to"], "defaultMetadata": {}},
    {"name": "tag", "superType": "meta", "description": "A tag for categorization",
     "allowedEdgeTypes": ["contains", "references"],
     "allowedAsTargetFor": ["contains"], "defaultMetadata": {}},
    {"name": "preference", "superType": "knowledge", "description": "A user preference",
     "allowedEdgeTypes": ["configures", "references"],
     "allowedAsTargetFor": ["configures"], "defaultMetadata": {}},
    {"name": "person", "superType": "entity", "description": "A person entity",
     "allowedEdgeTypes": ["related_to", "references", "belongs_to"],
     "allowedAsTargetFor": ["related_to", "references", "mentions"], "defaultMetadata": {}},
    {"name": "custom", "superType": "entity", "description": "A custom entity type",
     "allowedEdgeTypes": [], "allowedAsTargetFor": [], "defaultMetadata": {}},
]

DEFAULT_EDGE_TYPES = [
    {"name": "contains", "description": "Parent-child containment",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "produces", "description": "A produces B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "derives_from", "description": "A derives from B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "references", "description": "A references B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "belongs_to", "description": "A belongs to B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "generated", "description": "A generated B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "uses", "description": "A uses B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "mentions", "description": "A mentions B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "related_to", "description": "A is related to B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": False,
     "defaultMetadata": {}},
    {"name": "pinned", "description": "A is pinned to B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "sequences", "description": "A comes before B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "contributes_to", "description": "A contributes to B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "configures", "description": "A configures B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "observes", "description": "A observes B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "transforms", "description": "A transforms into B",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
    {"name": "custom", "description": "A custom edge type",
     "allowedSourceTypes": [], "allowedTargetTypes": [], "directional": True,
     "defaultMetadata": {}},
]
